apiVersion: v1
kind: Service
metadata:
  name: {{ include "goapp-demo.fullname" . }}
  labels:
{{ include "goapp-demo.labels" . | indent 4 }}
spec:
  #type: {{ .Values.service.type }}
  type: ClusterIP
  ports:
    - port: 5555
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "goapp-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
